"""empty message

Revision ID: 50700e9c91fa
Revises: 237503ed8b6e
Create Date: 2021-08-25 01:58:34.477717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50700e9c91fa'
down_revision = '237503ed8b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
