"""empty message

Revision ID: e322e8f2df18
Revises: 6e1a5bcaaba2
Create Date: 2021-08-22 21:28:30.783949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import update


# revision identifiers, used by Alembic.
revision = 'e322e8f2df18'
down_revision = '6e1a5bcaaba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE todos SET completed = False WHERE completed IS NULL;")
    op.alter_column('todos', 'completed', nullable=False)
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
